### ISSUE TITLE
JDK-8210970 : MathML editing issues in HTMLEditor

### ISSUE THREAD

**Issue by scientificware** [scientificware/jfx#4]
The purpose of this issue is to make mathematic editing as simple as possible.
----
This is referenced in Java Bug Database as
- [JDK-8210970 : MathML editing issues in HTMLEditor](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8210970)

This is tracked in JBS as 
- [JDK-8210970 : MathML editing issues in HTMLEditor](https://bugs.openjdk.java.net/browse/JDK-8210970)

> **Fluent Mathematic Writing.**

## Situation
Presently, the patch for JDK-8147476 ([javafxports/openjdk-jfx Rendering issues with MathML token elements.   w3c/mathml#117](https://github.com/javafxports/openjdk-jfx/pull/117#issue-196312277)) allows to display MathML formula in `WebView`. Consequently we can also work with MathML in `HTMLEditor`, the MathML rendering is pretty good.

## Justification
- A common user can not easily insert a mathematic formula in a `HTMLEditor`.
To insert this simple quadratic formula :
![screenshot_20180809_152818](https://user-images.githubusercontent.com/19194678/43902001-390a8cc0-9be9-11e8-982a-c7aa6ef41709.png)
 You need to insert the following code :
```
<math display="block"> 
   <mrow> 
      <mi>x</mi> 
      <mo>=</mo> 
      <mfrac> 
         <mrow> 
            <mo>−</mo> 
            <mi>b </mi> 
            <mo>±</mo> 
            <msqrt> 
               <mrow> 
                  <msup> 
                     <mi>b</mi> 
                     <mn>2</mn> 
                  </msup> 
                  <mo>−</mo> 
                  <mn>4</mn> 
                  <mi>a</mi> 
                  <mi>c</mi> 
               </mrow> 
            </msqrt> 
         </mrow> 
         <mrow> 
            <mn>2</mn> 
            <mi>a</mi> 
         </mrow> 
      </mfrac> 
   </mrow>
</math>
```
- trying to modify a formula will occurate some trouble in your document. Modifiy the previous formula, by removing 2a from the fraction ! ...

## Conclusions and Roadmap.
`HTMLEditor` and underlying `WebView` i.e. embedded `WebKit` implementation are clearly not ready yet for formula editing. It still needs some work to solve issues. 
- First : Identify all issues.
- Secondly : Understand where are problems.
- Third : Propose a solution.

## Details
- **Old known bug** All bug I encountered and who are already know, will be reported here.
  - [JDK-8170082](https://bugs.openjdk.java.net/browse/JDK-8170082) JavaFX clipboard erroneously supposes that text/??? are UTF-8.
  - [JDK-8133337](https://bugs.openjdk.java.net/browse/JDK-8133337) [Linux] Pasting HTML from Firefox does not work.
- **New bug not related to MathML** All new encountered bug independant from MathML use will be reported here.
- **MathML related bug** Some bugs couldn't be detected before JDK-8147476. They will be reported here. Since I work with HTMLEditor, I noticed that :
  - `HTMLEditor` doesn't create a new line when one presses Enter.
    - [x] Done. **Shouldn't affect JavaFX 11** :
      - It works with JavaFX 8u171 and JavaFX 11-internal+0-2018-07-02-110935
      - but not with JavaFX 9.0.4, JavaFX 10.0.1.  Post a message at openjfx-dev@openjdk.java.net because this affects HTMLEditor without the patch for JDK-8147476 too.
  - [ ] Deferred work. MathML content is not updated after an insertion. This only occurs when MathML Token are in a table like in the Mozilla MathML Torture Test.
  - [x] Work In Progress. Understood. Cursor disappears in `<mi>` token when the identifier name has only one character. If the name of the identifier is longer than 1 character, the cursor appears normaly. Note : in [W3C `<mi> `description](https://www.w3.org/TR/REC-MathML/chap3_2.html#sec3.2.2), The default font style should (typically) be "normal" (non-slanted) unless the content is a single character, in which case it should be "italic". This not occurs in `<mn>` and `<mo>`.  It's a WebCore issue, then transfered in my WebKit Repository [Issue\#1](https://github.com/scientificware/WebKit/issues/1).
  - [x] Work In Progress. Understood. In `<mo>`, the caret disappears too but only with the minus sign. Related to Hyphen. It's also a WebCore issue, then transfered in my WebKit Repository [Issue\#2](https://github.com/scientificware/WebKit/issues/2).
  - [ ] Work In Progress. Understood. The caret has the same size than the character (but not the font size, see https://github.com/javafxports/openjdk-jfx/issues/71#). This problem is specific to the MathML support. With normal text, the caret height is the font height. Solution : Anyway the implemented logic is not correct : the cursor size has to be equal to the parent `<row>` or `<math>` height (that's why, it is important to correct MathML code when loads a file or paste, see below about these `<row>` add and remove corrections). In the following example, move from the left to the right, you can see that the caret height is good outside the formula and too small inside : 
```
<p>Just a fraction example to test the Caret moves : 
   <math>
      <mrow>
         <mi>A</mi>
         <mo>=</mo>
         <mfrac>
            <mrow><mn>2</mn></mrow>
            <mrow><mn>8</mn></mrow>
         </mfrac>
         <mo>+</mo>
         <mfrac>
            <mrow>
               <mn>12</mn>
               <mo>-</mo>
               <mfrac>
                  <mrow><mn>567</mn></mrow>
                  <mrow><mn>17</mn></mrow>
               </mfrac>
            </mrow>
           <mrow><mn>37858727</mn></mrow>
         </mfrac>
      </mrow>
   </math>
. But you can do the calculus, if you want.
</p>
```
The caret height should be the same on the two pictures. Its height should be its height just after the word 'test'. That's the usual behavior. So, its size before '+' is wrong. May be a WebCore problem too so transfered to [Issue\#4](https://github.com/scientificware/WebKit/issues/4)
![screenshot_20180813_004449](https://user-images.githubusercontent.com/19194678/44007283-a4cf4af8-9e92-11e8-87c5-92ddba5d7452.png)
![screenshot_20180813_004544](https://user-images.githubusercontent.com/19194678/44007285-ae0872b6-9e92-11e8-9518-a2ce01bd4108.png)
  - no effect in `<mi>` token.
    ![screenshot_20180705_202453](https://user-images.githubusercontent.com/19194678/42340982-d68d5c98-8091-11e8-86fa-e961d513d9a2.png)
     - [x] Deferred work. Understood. In `<mi>` with only one character, css attributes are not apply. It's a WebCore issue too, then transfered in my WebKit Repository [Issue\#3](https://github.com/scientificware/WebKit/issues/3).
  - Correct selection logic. Some parts of the formula disappear, Selection should be only one rectangle not many rectangles like on the picture :
![screenshot_20180813_010713](https://user-images.githubusercontent.com/19194678/44007437-983d924c-9e95-11e8-96d8-bc29dc15e6aa.png)
See the same formula with my application ScientificPad, only one rectangle selection :
![screenshot_20180813_013337](https://user-images.githubusercontent.com/19194678/44007618-4785f23c-9e99-11e8-9808-6f30e3f0b28b.png)
     - [ ] Deferred work.
- **Enhancement** Mathematic edition needs to be improved (simply using keyboard)
  - making easiest the mathematic character insertions : 
    - [x] Done. Enable ∞, ∈, × , ⩽, α, ..., δ, ... ω, ..., Δ, ... simply using keyboard,
![screenshot_20180703_135132](https://user-images.githubusercontent.com/19194678/42218308-712a3148-7ec8-11e8-9fc9-c786ddbb16ca.png)
  - making easiest the mathematic formula insertions (simply using keyboard).
    - Firstly, I have to ask what is Igalia’s project about mathematic editing.
      - [x]  Done. No Igalia's project about that. According to their contracts, they concentrate their work on standard support rendering only. So I can go ahead.
    - In which part of the code, should I fix that ? In native WebCore, in native OpenJFX area or in Java OpenJFX area ?
      - [x] Done. First in Java OpenJFX area.
    - Roadmap :
      - Confort my point of vue 
        - [x] Done. I had a short conversation with a member of mathonweb group and F. Wang about that point. That conforts my point of vue.
      - Write an application for testing.
        - [X] Done. FXMath and FXMessages series (X1, X4).
      - Write the logic
        - Correct caret deplacements. Not a bug, but without other specification caret uses default the implementation. For example : in a fraction, when the caret is at the end of the numerator, if we press right arrow, the caret goes to the beginning of the denominator. But its right position should be rather immediately after the fraction.
          - [ ] Deferred work.
        - Use materials I developed in my own products and follow W3C recommendations about editing. Impove the minimal parser. Work In Progress.
          - Port the language register selection method : daily french and english, AsciiMath, OpenOffice Math and LaTex languages.

            - [ ] Work in progress. Presently, only daily French, German, Spanish, English languages are supported.
          - Port the Fluent Mathematic Writing logic.
            - [ ] Work In Progress.
![screenshot_20180805_123519](https://user-images.githubusercontent.com/19194678/43685077-7be45944-98ac-11e8-841d-f0e309851c5a.png)

Related to [HTMLEditor and MathML w3c/mathml#118](https://github.com/javafxports/openjdk-jfx/issues/118)

**Comment by scientificware** [comment]
```
<!DOCTYPE html>
<html>
   <head>
      <title>Page Title</title>
   </head>
   <body>
      <p>
         <math> 
            <mi>A</mi>
            <mo>=</mo>
            <mi>y</mi>
            <mo>&times</mo>
            <mi>sin</mi>
            <mfenced>
               <mrow>
                  <mi mathvariant="monospace">x</mi>
                  <mo>&times</mo>
                  <mi mathvariant="bold">&pi;</mi>
               </mrow>
             </mfenced>
         </math>
      </p>
      <h1>This is a Heading</h1>
      <p>This is a paragraph.</p>
   </body>
</html>
```

**Comment by scientificware** [comment]
Enchaînement des appels de méthodes : 

`RenderBlock` extends `RenderBox` and defines :

  - `paint` method (protected)
    - calls `paintObject` method

  - `paintObject` method (protected)
    - paints background, borders, ... with `RenderBox::paintBoxDecorations` method (public)
    - paints contents with `paintContents` method
    - paints selection with `paintSelection` method
    - paints floats with `paintFloats` method
    - paints outline with `paintOutline` method
    - paints continuation outlines
    - paints caret with `paintCaret` method

  - `paintContents` method (private)
    - paints child with paintInlineChildren or paintChildren methods.

According this render implementation none paint should be made after a call to the renderBlock paint method. MathML implementation doesn't respect this and paint or paintChildren method are overided and paint proceed direct painting. 

L'écriture mathématique implique que certaines chaines soient en italique par exemple le nom d'une variable. Mais ce n'est pas le cas pour le nom d'une fonction. Pour simplifer, l'implémentation actuelle considère que les variables d'un seul caractère sont bien des variables et elles sont affichées en italique par exemple `<mi>i</mi>` sera bien affiché _i_. Mais `<mi>in</mi>` ne sera pas affiché en italique.

**Comment by scientificware** [comment]
https://github.com/w3c/mathml : 
TeX2MathML converter implementation guidelines :

https://github.com/w3c/mathml-docs/issues/39
